name: Run JaCoCo

on:
  push:

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 02e0f5d0348e381a23c23909b2ec1e998de7ed9d
  
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Add Jacoco Maven Plugin and Edit Surefire Configuration
      if: runner.os == 'Linux'
      run: |
        # Add Jacoco Maven Plugin
        sed -i '/<\/plugins>/i \
            <plugin> \
                <groupId>org.jacoco<\/groupId> \
                <artifactId>jacoco-maven-plugin<\/artifactId> \
                <version>0.8.7<\/version> \
                <executions> \
                    <execution> \
                        <goals> \
                            <goal>prepare-agent<\/goal> \
                        <\/goals> \
                    <\/execution> \
                    <execution> \
                        <id>report<\/id> \
                        <phase>test<\/phase> \
                        <goals> \
                            <goal>report<\/goal> \
                        <\/goals> \
                    <\/execution> \
                <\/executions> \
            <\/plugin>' pom.xml

    - name: Add Jacoco Maven Plugin and Edit Surefire Configuration
      if: runner.os == 'macOS'
      run: |
        # Add Jacoco Maven Plugin
        sed -i '' '/<\/plugins>/i \
            <plugin> \
                <groupId>org.jacoco<\/groupId> \
                <artifactId>jacoco-maven-plugin<\/artifactId> \
                <version>0.8.5<\/version> \
                <executions> \
                    <execution> \
                        <goals> \
                            <goal>prepare-agent<\/goal> \
                        <\/goals> \
                    <\/execution> \
                    <execution> \
                        <id>report<\/id> \
                        <phase>test<\/phase> \
                        <goals> \
                            <goal>report<\/goal> \
                        <\/goals> \
                    <\/execution> \
                <\/executions> \
            <\/plugin>' pom.xml

        # Edit Surefire Plugin Configuration
        sed -i '' '/<artifactId>maven-surefire-plugin<\/artifactId>/a \
            <configuration> \
                <testFailureIgnore>true<\/testFailureIgnore> \
            <\/configuration>' pom.xml

    - name: Build project with JDK 17
      run: mvn test

    - name: Checkout Export Repository
      uses: actions/checkout@v2
      with:
        repository: flaky-dynamic-testing/jacoco-exports 
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Copy Jacoco Reports to new repository
      run: |
        mkdir /tmp/jacoco-reports
        find . -type d -path "*/target/site/jacoco" | while IFS= read -r dir; do
            # Find .html and .xml files within each directory
            find "$dir" -type f \( -name "*.html" -o -name "*.xml" \) -exec cp {} /tmp/jacoco-reports \;
        done
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        mkdir -p jacoco-exports/jacoco-reports-for-$REPO_NAME
        mv /tmp/jacoco-reports/ jacoco-exports/jacoco-reports-for-$REPO_NAME
        cd jacoco-exports
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Add Jacoco reports for $REPO_NAME"
        git push origin main
