name: Run JaCoCo

on:
  push:

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 02e0f5d0348e381a23c23909b2ec1e998de7ed9d
  
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Overwrite old pom.xml
      run: |
        curl -o new_pom.xml https://pastebin.com/raw/QZYrrT8C
        ls
